config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
    controllers: { registrations: 'registrations' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'posts#index'
  
  get '/users/:id', to: 'users#show', as: 'user'
  get 'users/:id/following', to: 'users#following', as: 'following'
  get 'users/:id/followers', to: 'users#followers', as: 'followers'

  resources :relationships, only: %i(create destroy)

    # ==========postsコントローラ、アクションののルーティング設定==========
    resources :posts, only: %i(new create index show destroy) do
      resources :photos, only: %i(create)

      resources :likes, only: %i(create destroy)
      
      resources :comments, only: %i(create destroy)
      
    end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  
  belongs_to :user
  belongs_to :post
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :post
  
  validates :user_id, uniqueness: { scope: :post_id }
end

app/models/photo.rb
class Photo < ApplicationRecord
  belongs_to :post

  validates :image, presence: true

  mount_uploader :image, ImageUploader
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :photos, dependent: :destroy
  
  has_many :likes, -> { order(created_at: :desc) }, dependent: :destroy
  has_many :comments, dependent: :destroy

  accepts_nested_attributes_for :photos
  
  def liked_by(user)
    # user_idとpost_idが一致するlikeを検索する
    Like.find_by(user_id: user.id, post_id: id)
  end  
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
  
  validates :follower_id, presence: true
  validates :followed_id, presence: true
end

app/models/user.rb
class User < ApplicationRecord

  has_many :posts, dependent: :destroy
  has_many :likes
  has_many :comments
  has_many :active_relationships, class_name:  "Relationship",
                                  foreign_key: "follower_id",
                                  dependent:   :destroy
  has_many :passive_relationships, class_name:  "Relationship",
                                   foreign_key: "followed_id",
                                   dependent:   :destroy
  has_many :following, through: :active_relationships, source: :followed
  has_many :followers, through: :passive_relationships, source: :follower
  
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
    # ==========パスワードなしでアップデートできる==========
  def update_without_current_password(params, *options)
    params.delete(:current_password)

    if params[:password].blank? && params[:password_confirmation].blank?
      params.delete(:password)
      params.delete(:password_confirmation)
    end

    result = update_attributes(params, *options)
    clean_up_passwords
    result
  end

  # ユーザーをフォローする
  def follow(other_user)
    active_relationships.create(followed_id: other_user.id)
  end
 
  # ユーザーをアンフォローする
  def unfollow(other_user)
    active_relationships.find_by(followed_id: other_user.id).destroy
  end
 
  # 現在のユーザーがフォローしてたらtrueを返す
  def following?(other_user)
    following.include?(other_user)
  end
         
  validates :name, presence: true, length: { maximum: 50 }
  validates :username, presence: true, uniqueness: true
  
  mount_uploader :profile_photo, ProfilePhotoUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  # ==========CSRF対策+nameカラム, usernameカラムをストロングパラメータへ==========
  protect_from_forgery with: :exception 
  
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :username, :profile_photo])
      devise_parameter_sanitizer.permit(:account_update, keys: [:name, :username, :profile_photo])
    end
  # ==========CSRF対策+nameカラム, usernameカラムをストロングパラメータへ==========
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  before_action :authenticate_user!
  
  def create
    @comment = Comment.new(comment_params)
    @post = @comment.post
    if @comment.save
      respond_to :js
    else
      flash[:alert] = "コメントに失敗しました"
    end
  end

  def destroy
    @comment = Comment.find_by(id: params[:id])
    @post = @comment.post
    if @comment.destroy
      respond_to :js
    else
      flash[:alert] = "コメントの削除に失敗しました"
    end
  end

  private
    def comment_params
      params.require(:comment).permit(:user_id, :post_id, :comment)
    end  
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  
  before_action :authenticate_user!
  
  def create
    @like = current_user.likes.build(like_params)
    @post = @like.post
    if @like.save
      respond_to :js
    end
  end
  
  def destroy
    @like = Like.find_by(id: params[:id])
    @post = @like.post
    if @like.destroy
      respond_to :js
    end
  end

  private
    def like_params
      params.permit(:post_id)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  
  before_action :authenticate_user!
  before_action :set_post, only: %i(show destroy)
  
  def index
    @posts = Post.limit(10).includes(:photos, :user).order('created_at DESC')
  end
  
  def show
  end
  
  def new
    @post = Post.new
    @post.photos.build
  end


  def create
    @post = Post.new(post_params)
    if @post.photos.present?
      @post.save
      redirect_to root_path
      flash[:notice] = "投稿が保存されました"
    else
      redirect_to root_path
      flash[:alert] = "投稿に失敗しました"
    end
  end
  
  def destroy
    if @post.user == current_user
      flash[:notice] = "投稿が削除されました" if @post.destroy
    else
      flash[:alert] = "投稿の削除に失敗しました"
    end
    redirect_to root_path
  end

  private
  
    def post_params
      params.require(:post).permit(:caption, photos_attributes: [:image]).merge(user_id: current_user.id)
    end
    
    def set_post
      @post = Post.find_by(id: params[:id])
    end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    
    def show
      @user = User.find_by(id: params[:id])
    end
     
    def following
      @title = "フォロー"
      @user  = User.find(params[:id])
      @users = @user.following
      render 'show_follow'
    end
 
    def followers
      @title = "フォロワー"
      @user  = User.find(params[:id])
      @users = @user.followers
      render 'show_follow'
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
    
      def avatar_url(user)
    return user.profile_photo unless user.profile_photo.nil?
    gravatar_id = Digest::MD5::hexdigest(user.email).downcase
    "https://www.gravatar.com/avatar/#{gravatar_id}.jpg"
      end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Traival
    = csrf_meta_tags
    = csp_meta_tag
    %meta{:content => "width=device-width, initial-scale=1", :name => "viewport"}/
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    #wrapper
      = render 'partial/navbar' if current_user
      - if flash[:notice]
        .alert.alert-info= flash[:notice]
      - if flash[:alert]
        .alert.alert-danger= flash[:alert]
      .container
        = yield
      = render 'partial/footer'

app/views/layouts/application.html_old.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Traival</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%# ==========ヘッダー、フラッシュメッセージ、フッター========== %>
    <div id="wrapper">
       <%= render 'partial/navbar' if current_user %>

       <% if flash[:notice] %>
         <div class="alert alert-info"><%= flash[:notice] %></div>
       <% end %>
       <% if flash[:alert] %>
         <div class="alert alert-danger"><%= flash[:alert] %></div>
       <% end %>

    <%# ==========ヘッダー、フラッシュメッセージ、フッター========== %>
    
    <%# ==========ここにcontainerクラスを追加========== %>
     <div class="container">
      <%= yield %>
     </div>
    <%# ==========containerクラス========== %>
    
    <%= render 'partial/footer' %>
    </div>
  </body>
</html>

app/views/pages/home.html.erb
<% if user_signed_in? %>
<%= link_to "サインアウト", destroy_user_session_path, method: :delete %>
<% end %>

<p>このページは仮のトップページです。</p>

<%= link_to "仮のボタンです", "#", class: "btn btn-primary" %>

app/views/pages/home.html.haml
- if user_signed_in?
  = link_to "サインアウト", destroy_user_session_path, method: :delete
%p このページは仮のトップページです。
= link_to "仮のボタンです", "#", class: "btn btn-primary"

app/views/pages/home.html_org.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

<% if user_signed_in? %>
<%= link_to "サインアウト", destroy_user_session_path, method: :delete %>
<% end %>

<p>このページは仮のトップページです。</p>

<%= link_to "仮のボタンです", "#", class: "btn btn-primary" %>

app/views/pages/home.html_org.haml
%h1 Pages#home
%p Find me in app/views/pages/home.html.erb
- if user_signed_in?
  = link_to "サインアウト", destroy_user_session_path, method: :delete
%p このページは仮のトップページです。
= link_to "仮のボタンです", "#", class: "btn btn-primary"

app/views/partial/_follow.html.haml
= form_for(current_user.active_relationships.build, remote: true) do |f|
  %div= hidden_field_tag :followed_id, @user.id
  = f.submit "フォローする", class: "follow-btn"

app/views/partial/_follow_form.html.haml
- unless @user == current_user
  #follow_form
    - if current_user.following?(@user)
      = render 'partial/unfollow'
    - else
      = render 'partial/follow'

app/views/partial/_footer.html.haml
%footer
  .container
    .text-center
      %p
        Copyright © Shotas

app/views/partial/_navbar.html.haml
%nav.navbar.navbar-expand-lg.navbar-light
  .container
    = link_to "", root_path, class: "navbar__brand navbar__mainLogo"
    %button.navbar-toggler{"aria-controls" => "navbarSupportedContent", "aria-expanded" => "false", "aria-label" => "Toggle navigation", "data-target" => "#navbarSupportedContent", "data-toggle" => "collapse", :type => "button"}
      %span.navbar-toggler-icon
    #navbarSupportedContent.collapse.navbar-collapse
      %ul.navbar-nav.ml-md-auto.align-items-center
        %li
          = link_to "投稿", new_post_path, class: "btn btn-primary"
        %li
          = link_to "", user_path(current_user), class: "nav-link commonNavIcon profile-icon"

app/views/partial/_stats.html.haml
- @user ||= current_user
.stats
  %a{:href => "#{following_path(@user)}"}
    フォロー
    %strong#following.stat
      = @user.following.count
  %a{:href => "#{followers_path(@user)}"}
    フォロワー
    %strong#followers.stat
      = @user.followers.count

app/views/partial/_unfollow.html.haml
= form_for(current_user.active_relationships.find_by(followed_id: @user.id), |
  html: { method: :delete }, remote:true) do |f|                             |
  = f.submit "フォロー中", class: "unfollow-btn"